### ISSUE TITLE
Summary: Grade = Exceeds Expectations

### ISSUE THREAD

**Issue by jordanwillis** [sandeepdhillo/TeaCozy#6]
Overall you did a fantastic job on this project!  You demonstrated that you are able to build a website from scratch based upon a static specification as well as create complex layouts using flexbox.

Have a look at my feedback and recommendations and see if you can start practicing those in your future projects.

Keep up the great work!

**Comment by sandeepdhillo** [comment]
Thanks Jordan for your elaborate review.I will definitely take care all the suggestions given by you, in future.
